Library.Web/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Library.Common.IServices;
using Library.Common.ViewModels.Book;
using Library.Common.ViewModels.Borrow;
using Library.Common.ViewModels.DictBookGenre;

namespace Library.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService bookService;

        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
            System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");

            System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("en-US");
        }

        //
        // GET: /Book/
        [HttpGet]
        public ActionResult Index()
        {
            IEnumerable<BookViewModel> bookList = this.bookService.GetBooks();
            return this.View(bookList);
        }

        [HttpPost]
        public ActionResult BookListJson([DataSourceRequest]
                                         DataSourceRequest request)
        {
            IEnumerable<BookViewModel> bookList = this.bookService.GetBooks();
            return this.Json(bookList.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
            
        [HttpPost]
        public ActionResult GetBookStatus(int id, [DataSourceRequest]
                                          DataSourceRequest request)
        {
            IQueryable<UserBorrowInfoModel> history = this.bookService.GetBookStatus(id);
            return this.Json(history.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetBookHistory(int id, [DataSourceRequest]
                                          DataSourceRequest request)
        {
            IQueryable<UserHistoryBorrowInfoModel> history = this.bookService.GetBookHistory(id);
            return this.Json(history.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult BookInfoDetails(int id)
        {
            BookInfoDetailsModel bookDetails = this.bookService.GetBookInfoDetails(id);
            return this.PartialView(bookDetails);
        }

        //
        // GET: /Book/Details/5
        [HttpGet]
        public ActionResult Details(int id)
        {
            BookDetailsModel bookDetails = this.bookService.GetBookDetails(id);
            return this.View(bookDetails);
        }

        //
        // GET: /Book/Create
        [HttpGet]
        public ActionResult Create()
        {
            return this.PartialView();
        }

        //
        // POST: /Book/Create
        [HttpPost]
        public ActionResult Create(BookAddModel newBook)
        {
            if (this.ModelState.IsValid)
            {
                int id = this.bookService.AddBook(newBook);
                return ResponseSuccesssJson(id);
            }
            return this.PartialView(newBook);
        }

        //
        // GET: /Book/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            BookEditModel book = this.bookService.GetBook(id);
            return this.PartialView(book);
        }

        //
        // POST: /Book/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, BookEditModel editedBook)
        {
            if (this.ModelState.IsValid)
            {
                editedBook.BookId = id;
                if (!this.ValidateBookCount(id, editedBook.Count))
                {
                    return this.PartialView();
                }
                this.bookService.EditBook(editedBook);
                return ResponseSuccesssJson();
            }
            return this.PartialView();
        }
        
        private bool ValidateBookCount(int id, int bookCount)
        {
            int count = this.bookService.GetBookBorrowCount(
                id);
            
            if (count > bookCount)
            {
                this.ModelState.AddModelError("Count", String.Format("Number of count cannt be less then {0}.", count));
                return false;
            }
            return true;
        }
        private ActionResult RedirectJsonAjax(string redirectUrl)
        {
            return this.Json(new
            {
                redirectUrl = redirectUrl,
                isRedirect = true
            });
        }
        private ActionResult RedirectJsonAjax(string action, string controller)
        {
            return this.Json(new
            {
                redirectUrl = Url.Action(action, controller),
                isRedirect = true
            });
        }
        private ActionResult ResponseSuccesssJson()
        {
            return this.Json(new
            {
                isSuccess = true
            });
        }
        private ActionResult ResponseSuccesssJson(string message)
        {
            return this.Json(new
            {
                isSuccess = true,
                message = message
            });
        }
        private ActionResult ResponseSuccesssJson(int message)
        {
            return this.Json(new
            {
                isSuccess = true,
                message = message
            });
        }


    }
}

Library.Web/Controllers/BorrowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Library.Common.Exceptions;
using Library.Common.IServices;
using Library.Common.ViewModels.Book;
using Library.Common.ViewModels.Borrow;
using Library.Common.ViewModels.DictBookGenre;
using Library.Common.Extensions;

namespace Library.Web.Controllers
{
    public class BorrowController : Controller
    {
        private readonly IBookService bookService;
        private readonly IBorrowService borrowService;
        private readonly IUserService userService;

        public BorrowController(IBookService bookService,
            IBorrowService borrowService,
            IUserService userService)
        {
            this.bookService = bookService;
            this.borrowService = borrowService;
            this.userService = userService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult BorrowedBooks()
        {
            return View();
        }

        [HttpGet]
        public ActionResult BorrowBook()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult BorrowBooks(int userId, int[] books)
        {
            try
            {
                borrowService.BorrowBooks(userId, books);
            }
            catch (UserActiveException ex)
            {
                return this.ResponseFailureJson(ex.Message);
            }
            catch (BorrowException ex)
            {
                return this.ResponseFailureJson(ex.Message);
            }
            return this.ResponseSuccessJson();
        }

        [HttpPost]
        public ActionResult BookBorrowedJson([DataSourceRequest]
                                             DataSourceRequest request)
        {
            IQueryable<BookBorrowedByUserModel> books = this.bookService.GetBorrowedBooks();
            return this.Json(books.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetBorrowedBooksByUserJson([DataSourceRequest]
                                                       DataSourceRequest request, int id)
        {
            IQueryable<BookBorrowedReturnModel> books = this.borrowService.GetBorrowedBooksByUser(id);
            return this.Json(books.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetAviableBooksForUser(int id)
        {
            var books = this.bookService.GetAviableBooksForUser(id);
            IEnumerable<SelectListItem> booksEnumerable = 
                books.Select(c => new SelectListItem { Text = c.Value, Value = c.Key.ToString() }).AsEnumerable();
            if (booksEnumerable.FirstOrDefault() == null)
            {
                return this.ResponseFailureJson("No records for this user!");
            }
            return this.ResponseSuccessJson(this.Json(booksEnumerable));
        }

        [HttpGet]
        public ActionResult GetAviableUsers([DataSourceRequest]
                                            DataSourceRequest request)
        {
            var users = this.userService.GetAviableUsers();
            IEnumerable<SelectListItem> usersEnumerable = users.Select(c => new SelectListItem { Text = c.Key.ToString(), Value = c.Value }).AsEnumerable();
            return Json(usersEnumerable, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult UsersWithBooks()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UsersWithBooksJson([DataSourceRequest]
                                               DataSourceRequest request)
        {
            IQueryable<UserBorrowCountModel> books = this.userService.GetUsersWithBooks();
            return this.Json(books.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ReturnBook(int id)
        {
            this.borrowService.ReturnBook(id);
            return ResponseSuccessJson();
        }

        [HttpPost]
        public ActionResult ReturnBooks(int[] id)
        {
            if (id == null)
            {
                return ResponseJson("nonBooks", "Zaznacz se jakies ksiazki!");
            }
            this.borrowService.ReturnBooks(id);
            return ResponseSuccessJson();
        }

        private ActionResult ResponseJson(string status, string message)
        {
            return this.Json(new
            {
                status = status,
                message = message
            });
        }

        private ActionResult ResponseFailureJson(string message)
        {
            return this.ResponseJson("failure", message);
        }

        private ActionResult ResponseSuccessJson(string message)
        {
            return this.ResponseJson("success", message);
        }

        private ActionResult ResponseSuccessJson()
        {
            return this.ResponseJson("success", string.Empty);
        }

        private ActionResult ResponseSuccessJson(JsonResult json)
        {
            return this.Json(new
            {
                status = "success",
                message = json
            });
        }
    }
}

Library.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Library.Common.IServices;
using Library.Common.ViewModels.User;

namespace Library.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService _userService)
        {
            this.userService = _userService;
        }

        //
        // GET: /User/
        [HttpGet]
        public ActionResult Index()
        {
            IEnumerable<UserViewModel> userList = this.userService.GetUsers();
            return this.View(userList);
        }

        //
        // GET: /User/Details/5
        [HttpGet]
        public ActionResult Details(int id)
        {
            UserDetails user = this.userService.GetUserDetails(id);
            return this.View(user);
        }

        //
        // GET: /User/CreateC:\Users\chrystian.kislo\Documents\Visual Studio 2012\Projects\LibraryProject\Library.Web\Controllers\UserController.cs
        [HttpGet]
        public ActionResult Create()
        {
            return this.View();
        }

        //
        // POST: /User/Create
        [HttpPost]
        public ActionResult Create(NewUserModel newUser)
        {
            this.userService.AddUser(newUser);
            return this.RedirectToAction("Index");
        }

        //
        // GET: /User/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            EditUserModel user = this.userService.GetUser(id);
            return this.View(user);
        }

        //
        // POST: /User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EditUserModel editedUser)
        {
            editedUser.UserId = id;
            this.userService.EditUser(editedUser);
            return this.RedirectToAction("Index");
        }

        //
        // GET: /User/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            UserDetails user = this.userService.GetUserDetails(id);
            return this.View(user);
        }

        //
        // POST: /User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            this.userService.DeleteUser(id);
            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UserInfoDetails(int id)
        {
            UserInfoDetailsModel userDetails = this.userService.GetBookInfoDetails(id);
            return this.PartialView(userDetails);
        }
    }
}

Library.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <script src="~/Scripts/modernizr-2.6.2.js"></script>

        <link href="@Url.Content("~/Content/kendo/2015.2.624/kendo.common.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/kendo/2015.2.624/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/kendo/2015.2.624/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/kendo/2015.2.624/kendo.default.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/kendo/2015.2.624/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/kendo/2015.2.624/jquery.min.js")"></script>
        <script src="@Url.Content("~/Scripts/kendo/2015.2.624/jszip.min.js")"></script>
        <script src="@Url.Content("~/Scripts/kendo/2015.2.624/kendo.all.min.js")"></script>
        <script src="@Url.Content("~/Scripts/kendo/2015.2.624/kendo.aspnetmvc.min.js")"></script>

        <style>
            ul#menu >li >a:hover
            {
                background-image: linear-gradient(#FFF 0%, #444 40%, #444 60%, #FFF 100%);
                color: white;
            }
            ul#menu
            {
                width: 80%;
                margin: 0 auto;
                padding: 0;
                list-style-type: none;
            }
            ul#menu > li
            {
                float: left;
            }
            ul#menu > li > a
            {
                margin-top: 15px;
                margin-bottom: 15px;
                padding: 15px; 
                height: 60px;
                text-decoration: none;
                text-align: center;
                display: block;
                color: #000;
                box-shadow: 0 0 0 1px #FFF inset;
                background-image: linear-gradient(#FFF 0%, #EEE 30%, #DDD 70%, #FFF 100%);
            }
            #menu > li:hover > a
            {
                color: #00F;
                background-color: #FFF;
            }
            ul#menu > li:nth-child(even)
            {
        
            }
        
            ul#menu > li:nth-child(odd)
            {
        
            }
            ul#menu:after
            {
                content: '';
                display: block;
                clear: both;
            }
            ul > li
            {
                width: 20%;
            }
        </style>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Borrow", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

        <ul id="menu">
            <li>
                @Html.ActionLink("Users", "Index", "User")
            </li>
            <li>
                @Html.ActionLink("Books", "Index", "Book")
            </li>
            <li>
                @Html.ActionLink("Borrowed Books", "BorrowedBooks", "Borrow")
            </li>
            <li>
                @Html.ActionLink("Users with Books", "UsersWithBooks", "Borrow")
            </li>
            <li id="borrowBookLink">
                <a href="#">Borrow Book</a>
            </li>
        </ul>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        <!--<script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>-->
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jqueryval")

@(Html.Kendo().Window().Name("BorrowBooks").Visible(false)
)
        <script type="text/javascript">
            $(document).ready(function () {
                kendo.culture("pl-PL");
                $("#borrowBookLink :first-child").click(function () {
                var urlAction = "@Url.Action("BorrowBook", "Borrow")";
                var wnd =
                    $("#BorrowBooks")
                        .kendoWindow({
                                         content: urlAction,
                                         visable: true,
                                         width: 400,
                                         modal: true,
                                         position: {
                                top: "10%",
                                left: "40%"
                            }
                                     }).data("kendoWindow")
                        .title("Borrow Books").open();
                });
            });
        </script>
    
    </body>
</html>